### ISSUE TITLE
V2版本无法执行

### ISSUE THREAD

**Issue by 0xqq** [mrzhangboss/FlinkSQLPlatform#7]
![image](https://user-images.githubusercontent.com/16940356/72676472-92de4100-3acc-11ea-867b-f96e957e5b10.png)
![image](https://user-images.githubusercontent.com/16940356/72676474-97a2f500-3acc-11ea-91f9-b3b386d8df9e.png)

**Comment by mrzhangboss** [comment]
文档还在持续维护中，这个错误是因为你写错了表名，将SQL改成
`select * from iris_mysql`就行了，你可以使用`show tables` 查看所以表名
